version: '3.8'

services:
  database:
    image: postgres:17
    container_name: database
    restart: always
    env_file:
      - .env  # Load environment variables from .env file
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
